# Been writing some YAML during my internship at IDEXX. Finally have a chance to use it in a personal project!

name: CI

# Run this script every time something is pushed to a branch or main
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  code_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11.8' # Running this locally

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
        
      - name: Install dependencies from lock file
        run: |
          poetry install

      - name: Run linting and type checking
        run: |
          ./code_check.sh
